version: '3.9'
services:
  config-service:
    container_name: config-service
    pull_policy: always
    healthcheck:
      test: "curl --fail --silent localhost:9297/actuator/health/readiness | grep UP || exit 1"
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 10s
    build:
      context: config-service
      dockerfile: Dockerfile
    image: config-service:latest
    ports:
      - "9297:9297"
    networks:
      - spring-cloud-network
  discovery-service:
    container_name: discovery-service
    depends_on:
      config-service:
        condition: service_healthy
    build:
      context: discovery-service
      dockerfile: Dockerfile
    image: discovery-service:latest
    ports:
      - 8761:8761
    networks:
      - spring-cloud-network

  gateway-service:
    container_name: gateway-service
    depends_on:
      config-service:
        condition: service_healthy
    build:
      context: gateway-service
      dockerfile: Dockerfile
    image: gateway-service:latest
    ports:
      - 8080:8080
    networks:
      - spring-cloud-network
  user-service:
    container_name: user-service
    depends_on:
      config-service:
        condition: service_healthy
    build:
      context: user-service
      dockerfile: Dockerfile
    image: user-service:latest
    ports:
      - 9002:9002
    networks:
      - spring-cloud-network
  auth-service:
    container_name: auth-service
    depends_on:
      config-service:
        condition: service_healthy
    build:
      context: auth-service
      dockerfile: Dockerfile
    image: auth-service:latest
    ports:
      - 9001:9001
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge
