server:
  port: 9002

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb+srv://root:RootRoot@test-cluster.5bgmz5v.mongodb.net/user-db?retryWrites=true&w=majority


jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400
