server:
  port: 9297

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kpavlunenko/bas-configs.git
          clone-on-start: true
          username: config_server
          password: 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

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "health,refresh"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
